unhardcode API_HOST in nginx
JeffreyCA/spleeter-web pull request #115
Opened 2022-01-13 02:39 UTC by jtagcat

Closes #114

2022-01-13 05:39 UTC, JeffreyCA commented
Hi, thanks for adding this. Can you add the same to docker-compose.yml and the README?

2022-01-13 10:31 UTC, jtagcat commented
Done, also added default in the nginx Dockerfile.

2022-01-15 06:08 UTC, JeffreyCA requested changes
Great thank you! I believe you're the first community contributor 😊

2022-01-15 06:08 UTC, JeffreyCA commented on README.md
> +| `APP_HOST` | Domain name or public IP of server. This is only used for production builds (i.e. when `DJANGO_DEVELOPMENT` is not set)
```suggestion
| `APP_HOST` | Domain name or public IP of server. This is only used for production builds (i.e. when `DJANGO_DEVELOPMENT` is not set) |
```

2022-01-15 06:08 UTC, JeffreyCA commented on README.md
> +| `API_HOST` | Hostname of API server (for nginx)
```suggestion
| `API_HOST` | Hostname of API server (for nginx) |
```

2022-01-15 07:07 UTC, jtagcat commented
If you start counting from zero (you), then yes.

2022-01-15 07:50 UTC, merged