Monkey patch to spleeter so it follows redirects for model downloading
JeffreyCA/spleeter-web pull request #949
Opened 2024-01-28 03:10 UTC by microtherion

At the moment, `spleeter` model downloads are failing, at least for me, because:
* `spleeter` models when downloaded from github go through a redirection.
* `spleeter-web` specifies a `httpx` dependency of 0.26.0.
* As of 0.20.0, `httpx` no longer follows redirects by default.
* `spleeter` fails to explicitly request following redirects.

This issue has been called out in an unmerged `spleeter` PR: https://github.com/deezer/spleeter/pull/808 but that has not been merged for a long time.

One possible solution might be to downgrade the `httpx` dependency to < 0.20.0, but I don't know what other repercussions this could have. The other solution, which I've chosen here, is to fix the `spleeter` code with a patch applied at container build time.

2024-01-28 04:26 UTC, JeffreyCA requested changes
Thanks for the fix and catching this! This was actually a regression in the recent release and the version of `httpx` being installed before was 0.19.0. Could we downgrade it instead in `requirements.txt`?

2024-01-30 20:26 UTC, microtherion commented
Sure, I'll try that. I assumed there was a reason for the version bump, so I did not investigate that avenue. But should there be safeguards in place to avoid a repetition of this problem?

2024-01-31 16:57 UTC, JeffreyCA commented
There's a `dependabot.yml` we can add `httpx` to

2024-02-01 12:17 UTC, microtherion commented
I verified that pinning `httpx` to 0.19.0 works. I hope the dependabot change is correct — I have no experience with that and would not know how to test it.

2024-02-02 02:31 UTC, merged

2024-02-02 02:31 UTC, JeffreyCA commented
Perfect, thanks again!